name: module_architecture_mobile
version: 1.0.0+1
publish_to: "none"
description: "A new Flutter project."

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  # packages
  merge_dependencies:
    path: packages/merge_dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  analysis_lints: any

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/AppIcons.ttf

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
