name: more
version: 0.0.1
homepage: "none"
publish_to: "none"
description: "A new Flutter project."

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  # packages
  core:
    path: ../../packages/core
  components:
    path: ../../packages/components
  navigation:
    path: ../../packages/navigation

dev_dependencies:
  flutter_test:
    sdk: flutter
  analysis_lints: ^1.0.9

flutter:
  uses-material-design: true
