name: merge_dependencies
version: 0.0.1
homepage: "none"
publish_to: "none"
description: "A new Flutter project."

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  # packages
  core:
    path: ../core
  navigation:
    path: ../navigation
  base_dependencies:
    path: ../base_dependencies
  # modules
  main:
    path: ../../modules/main
  others:
    path: ../../modules/others
  more:
    path: ../../modules/more

dev_dependencies:
  flutter_test:
    sdk: flutter
  analysis_lints: ^1.0.3

flutter:
  uses-material-design: true
