name: merge_dependencies
version: 0.0.1
homepage: "none"
publish_to: "none"
description: "A new Flutter project."

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  # chuck
#  chuck_interceptor: ^2.3.3
  # packages
  core:
    path: ../core
  components:
    path: ../components
  navigation:
    path: ../navigation
  # modules
  auth:
    path: ../../modules/auth
  home:
    path: ../../modules/home
  initial:
    path: ../../modules/initial
  main:
    path: ../../modules/main
  more:
    path: ../../modules/more
  system:
    path: ../../modules/system

dev_dependencies:
  flutter_test:
    sdk: flutter
  analysis_lints: ^1.0.5

flutter:
  uses-material-design: true
