name: components
version: 0.0.1
homepage: "none"
publish_to: "none"
description: "A new Flutter project."

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  # intl  
  intl: ^0.20.2
  # rx
  rxdart: ^0.28.0
  # cached network image
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  analysis_lints: ^1.0.9

flutter:
  uses-material-design: true
