name: core
version: 0.0.1
homepage: "none"
publish_to: "none"
description: "A new Flutter project."

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # packages
  components:
    path: ../components
  navigation:
    path: ../navigation
  base_dependencies:
    path: ../base_dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  analysis_lints: ^1.0.5
  mocktail: ^1.0.4

flutter:
  generate: true
  uses-material-design: true

