name: core
version: 0.0.1
homepage: "none"
publish_to: "none"
description: "A new Flutter project."

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  # di
  get_it: ^9.2.1
  # equatable
  equatable: ^2.0.8
  # state
  rxdart: ^0.28.0
  flutter_bloc: ^9.1.1
  # hive
  hive_ce: ^2.19.3
  flutter_secure_storage: ^10.0.0
  # path
  path_provider: ^2.1.5
  # rest api
  dio: ^5.9.1
  # url launchers
  url_launcher: ^6.3.2
  # otp autofill
  pinput: ^6.0.2
  smart_auth: ^3.2.0
  # connectivity plus
  connectivity_plus: ^7.0.0
  # package info
  package_info_plus: ^9.0.0
  # cached network image
  flutter_cache_manager: ^3.4.1
  # firebase
  firebase_core: ^4.4.0
  firebase_analytics: ^12.1.2
  firebase_messaging: ^16.1.1
  firebase_remote_config: ^6.1.4
  # local notification
  flutter_local_notifications: ^20.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  analysis_lints: ^1.0.9
  mocktail: ^1.0.4

flutter:
  generate: true
  uses-material-design: true

