name: auth
version: 0.0.1
homepage: "none"
publish_to: "none"
description: "Authentication module."

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  # packages
  core:
    path: ../../packages/core
  components:
    path: ../../packages/components
  navigation:
    path: ../../packages/navigation

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  bloc_test: ^10.0.0
  analysis_lints: ^1.0.9

flutter:
  uses-material-design: true