name: navigation
version: 0.0.1
homepage: "none"
publish_to: "none"
description: "A new Flutter project."

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  # external packages
  chuck_interceptor: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  analysis_lints: ^1.0.5

flutter:
  uses-material-design: true
